server:
  port: 8000
spring:
  profiles:
    active: dev
    include: feign # 加载application-feign.yml配置文件
  application:
    name: service-order
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        namespace: ${spring.profiles.active:dev} # 动态取值，而且默认是dev

# 开启日志，打印com.order.feign包对应的日志
logging:
  level:
    com.dgq.order.feign: debug
---
spring:
  config:
    import:
      - nacos:common.properties?group=order
      - nacos:database.properties?group=order
    activate:
      on-profile: dev

#---
#spring:
#  config:
#    import:
#      - nacos:common.properties?group=order
#      - nacos:database.properties?group=order
#    activate:
#      on-profile: test
#
#---
#spring:
#  config:
#    import:
#      - nacos:common.properties?group=order
#      - nacos:database.properties?group=order
#    activate:
#      on-profile: prod