#配置OpenFeign
spring:
  cloud:
    openfeign:
      client:
        config:
          # 配置默认超时时间，没有配置的feign客户端，使用默认值
          default:
            connect-timeout: 1000
            read-timeout: 2000
          # 配置某个具体ProductFeignClient的超时时间
          service-product: # 和ProductFeignClient中value指定的值一样
            logger-level: full
            connect-timeout: 3000
            read-timeout: 5000
#            request-interceptors:
#              - com.dgq.order.interceptor.XTokenRequestInterceptor
#            retryer: feign.retryer.Default
    sentinel:
      transport:
        dashboard: localhost:8080
      eager: true #提前加载，项目启动，自动连上sentinel控制台

# 开启熔断功能，openfeign fallback功能
feign:
  sentinel:
    enabled: true