spring:
  cloud:
    gateway:
      routes:
        - id: bing-route
          uri: https://cn.bing.com
          predicates:
            - Path=/**
          order: 10
        - id: order
          uri: lb://service-order
          predicates:
            - Path=/api/order/**
          order: 1
        - id: product
          uri: lb://service-product
          predicates:
            - Path=/api/product/**
          order: 2